// Code generated by protoc-gen-leaf. DO NOT EDIT.
// versions:
// - protoc-gen-leaf v0.0.1
// - protoc                v4.25.3
// source: proto/user/user.proto

package user

import (
	context "context"
	chanrpc "github.com/uc1024/leaf/chanrpc"
	gate "github.com/uc1024/leaf/gate"
	module "github.com/uc1024/leaf/module"
	network "github.com/uc1024/leaf/network"
	iprotobuf "github.com/uc1024/leaf/network/iprotobuf"
	reflect "reflect"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = module.NewModulesMaster
var _ = context.Background
var _ = reflect.TypeOf
var _ = chanrpc.NewClient
var _ = network.Processor.Route
var _ = iprotobuf.NewProcessor
var _ = gate.NewGateModule

type IUserModule interface {

	// Info Info
	//
	// # 用户信息
	//
	// - 用户信息
	//
	Info(ctx context.Context, req *InfoReq, rsp *InfoRsp) (err error)

	// Login login
	Login(ctx context.Context, req *InfoReq, rsp *InfoRsp) (err error)
}

// * RegisterLeaf 注册消息
func RegisterUserModuleMessage(processor *iprotobuf.Processor, skeleton *module.Skeleton, m IUserModule, rpc *chanrpc.Server) {

	processor.Register(100, &InfoReq{})
	processor.Register(101, &InfoRsp{})
	processor.SetRouter(&InfoReq{}, rpc)
	skeleton.RegisterChanRPC(reflect.TypeOf(&InfoReq{}), func(args []interface{}) {
		request := args[0].(*InfoReq)
		_ = request
		// * agent conn
		agent := args[1].(gate.Agent)

		if !agent.Auth() {
			agent.Close()
			return
		}
		ctx := context.WithValue(context.Background(), "agent", agent)
		response := &InfoRsp{}

		err := m.Info(ctx, request, response)
		if err != nil {
			agent.Close()
			return
		}
		agent.WriteMsg(response)
	})

	processor.Register(102, &InfoReq{})
	processor.Register(103, &InfoRsp{})
	processor.SetRouter(&InfoReq{}, rpc)
	skeleton.RegisterChanRPC(reflect.TypeOf(&InfoReq{}), func(args []interface{}) {
		request := args[0].(*InfoReq)
		_ = request
		// * agent conn
		agent := args[1].(gate.Agent)

		ctx := context.WithValue(context.Background(), "agent", agent)
		response := &InfoRsp{}

		err := m.Login(ctx, request, response)
		if err != nil {
			agent.Close()
			return
		}
		agent.WriteMsg(response)
	})
}
